version: '3.2'
services:
  pms-mysql:
    # disabling line below as image info is given in file - Dockerfile.MySql
    # image: mysql:8.0
    container_name: pms-mysql
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.MySql
    command: [ 'mysqld' ]
    environment:
      MYSQL_USER: centric
      MYSQL_PASSWORD: centric
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: products
    ports:
      - "3308:3306"
